const defaultData={site:{school:'โรงเรียนของเรา',year:'2026',mainColor:'#d6613d',title:'ความทรงจำ\nไม่เคยจบ',heroText:'พื้นที่สำหรับเก็บเรื่องราว รอยยิ้ม และมิตรภาพของพวกเรา',coverImage:'',footer:'สร้างด้วยความทรงจำของพวกเรา'},students:[{name:'พิมพ์ชนก วัฒนชัย',detail:'มินท์ · 6/1',quote:'ทุกความทรงจำมีความหมาย'},{name:'ธนกฤต ศรีสุข',detail:'นนท์ · 6/1',quote:'เจอกันใหม่ในวันที่ฝันเป็นจริง'},{name:'ณิชาภา บุญมี',detail:'ฟ้า · 6/2',quote:'ยิ้มให้กับทุกวัน'},{name:'ณัฐวุฒิ เจริญผล',detail:'บอส · 6/2',quote:'มิตรภาพไม่มีวันจบ'}],gallery:[{caption:'วันปัจฉิมนิเทศ',image:'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=900&q=80'},{caption:'มิตรภาพของพวกเรา',image:'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=900&q=80'},{caption:'กีฬาสีของเรา',image:'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=900&q=80'}]};
let data=JSON.parse(localStorage.getItem('yearbook-data')||'null')||structuredClone(defaultData);const $=id=>document.getElementById(id),save=()=>localStorage.setItem('yearbook-data',JSON.stringify(data)),escape=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function publicPage(){if(!$('studentGrid'))return;let s=data.site;document.documentElement.style.setProperty('--accent',s.mainColor||'#7c4dff');$('yearLabel').textContent=`CLASS OF ${s.year}`;$('schoolCover').textContent=s.school;$('yearCover').textContent=s.year;$('heroTitle').innerHTML=escape(s.title).replace('\n','<br>');$('heroText').textContent=s.heroText;$('footerText').textContent=s.footer;const cover=document.querySelector('.book');cover.style.backgroundImage=s.coverImage?`linear-gradient(#0003,#0003),url('${s.coverImage}')`:'';cover.classList.toggle('image-cover',Boolean(s.coverImage));const show=()=>{$('studentGrid').innerHTML=data.students.filter(x=>(x.name+x.detail).toLowerCase().includes($('search').value.toLowerCase())).map(x=>`<article class="student">${x.image?`<img class="student-photo" src="${escape(x.image)}" alt="รูปของ ${escape(x.name)}">`:`<div class="student-placeholder">${escape(x.name.charAt(0))}</div>`}<h3>${escape(x.name)}</h3><p>${escape(x.detail)}</p>${x.quote?`<blockquote>“${escape(x.quote)}”</blockquote>`:''}</article>`).join('')};$('search').oninput=show;show();$('galleryGrid').innerHTML=data.gallery.map(x=>`<div class="gallery-item" style="background-image:url('${escape(x.image)}')">${escape(x.caption)}</div>`).join('')}
function adminPage(){if(!$('loginCard'))return;const logged=localStorage.getItem('yearbook-admin')==='true';if(logged)showDashboard();$('loginForm').onsubmit=e=>{e.preventDefault();let password=$('password').value,stored=localStorage.getItem('yearbook-password');if(!stored){localStorage.setItem('yearbook-password',password)}else if(stored!==password){alert('รหัสผ่านไม่ถูกต้อง');return}localStorage.setItem('yearbook-admin','true');showDashboard()};$('logout').onclick=()=>{localStorage.removeItem('yearbook-admin');location.reload()};$('siteForm').onsubmit=e=>{e.preventDefault();data.site=Object.fromEntries(new FormData(e.target));save();alert('บันทึกแล้ว')};$('studentForm').onsubmit=e=>{e.preventDefault();data.students.unshift(Object.fromEntries(new FormData(e.target)));save();e.target.reset();renderAdminLists()};$('galleryForm').onsubmit=e=>{e.preventDefault();data.gallery.unshift(Object.fromEntries(new FormData(e.target)));save();e.target.reset();renderAdminLists()};$('dashboard').onclick=e=>{let button=e.target.closest('[data-delete]');if(!button)return;data[button.dataset.delete].splice(Number(button.dataset.index),1);save();renderAdminLists()}}
function showDashboard(){$('loginCard').hidden=true;$('dashboard').hidden=false;Object.entries(data.site).forEach(([key,value])=>$('siteForm').elements[key].value=value);$('siteForm').elements.mainColor.value=data.site.mainColor||'#d6613d';renderAdminLists()}function renderAdminLists(){$('studentList').innerHTML=data.students.map((x,i)=>`<div class="list-row">${escape(x.name)}<button class="delete" data-delete="students" data-index="${i}">ลบ</button></div>`).join('');$('galleryList').innerHTML=data.gallery.map((x,i)=>`<div class="list-row">${escape(x.caption)}<button class="delete" data-delete="gallery" data-index="${i}">ลบ</button></div>`).join('')}
if ($('coverFile')) $('coverFile').addEventListener('change', event => { const file = event.target.files[0]; if (!file) return; if (file.size > 3 * 1024 * 1024) return alert('กรุณาเลือกไฟล์ขนาดไม่เกิน 3 MB'); const reader = new FileReader(); reader.onload = () => { $('siteForm').elements.coverImage.value = reader.result; }; reader.readAsDataURL(file); });
if ($('studentFile')) $('studentFile').addEventListener('change', event => { const file = event.target.files[0]; if (!file) return; if (file.size > 3 * 1024 * 1024) return alert('กรุณาเลือกไฟล์ขนาดไม่เกิน 3 MB'); const reader = new FileReader(); reader.onload = () => { $('studentForm').elements.image.value = reader.result; }; reader.readAsDataURL(file); });
publicPage();adminPage();
if (data.site.mainColor === '#d6613d' || !data.site.mainColor) { data.site.mainColor = '#7c4dff'; save(); if ($('studentGrid')) document.documentElement.style.setProperty('--accent', data.site.mainColor); }
window.addEventListener('storage', event => { if (event.key === 'yearbook-data' && $('studentGrid')) { data = JSON.parse(event.newValue); publicPage(); } });
